### ISSUE TITLE
Lazy catchall for open branches

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Shell-Scripts#29]
I have a bunch of hanging branches out there with unfinished work and without associated PRs yet. As of this writing, here's what's out there and what it's for:

* [x] `f/composer-install` - Adds a "robust" script to wrap around `composer install`. Ironically, it can't be used to install this package since you would have had to already run `composer install` by hand. Low priority. merged in #35.
* [x] `f/tmp-dir-permissions` - The result of problems encountered on AWS environments where the default PHP temp dir doesn't actually exist, causing strange session errors. The associated script was designed to be run during `update` to ensure the tmp folder was always present. Merged in #34.
* [ ] `f/debug-toggle` - The intention is to have a script that can rewrite your `core.php` file's `debug` entry for you in staging or production, to speed up temporary SQL log or DebugKit captures in production. The thinking is that running the script should "toggle" the value between >0 and 0, remembering the previous "setting". This should be pretty easily possible with `sed` or `awk`.
* [ ] `f/docs-post` - A counterpart to [beporter/docs-manager](https://github.com/beporter/docs-manager). This script should be able to ZIP up a directory containing generated code coverage HTML files, and POST it to a webserver script that can extract it and host it. The goal here is that our Travis build would be able to load coverage reports for a specific branch onto loadsysdev.com in a lightly protected manner so we (and/or our clients) can review it.
* [x] `b/misc-fixes` - A couple improvements/notes to follow up on. Merged in #33.

**Comment by beporter** [comment]
Going to close this out. There's a PR for docs-post (#56), and debug-toggle isn't really relevant any more with app-local.php config files.
